<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Acc_Matching_PolicyNo_TextBox</name>
   <tag></tag>
   <elementGuidId>d104c9fb-ca22-4e26-8dde-480dc5401821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='bAccUnPolNumUM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='bAccUnPolNumUM']</value>
   </webElementProperties>
</WebElementEntity>
