<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox</name>
   <tag></tag>
   <elementGuidId>114a10ed-06a4-4147-8af8-cc336b895c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table//input[@class='TrChkClass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table//input[@class='TrChkClass']</value>
   </webElementProperties>
</WebElementEntity>
