<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SelectEntity</description>
   <name>Entity</name>
   <tag></tag>
   <elementGuidId>34be9cd0-ae96-477d-9194-bf168898d5f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='entity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='entity']</value>
   </webElementProperties>
</WebElementEntity>
