<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PolicyNoSearchFields</description>
   <name>SearchFields</name>
   <tag></tag>
   <elementGuidId>0398c3db-5231-4590-a436-c0d84f0c8601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='gs_policy_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='gs_policy_no']</value>
   </webElementProperties>
</WebElementEntity>
