<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SaveButton</description>
   <name>Save</name>
   <tag></tag>
   <elementGuidId>6893191b-09cd-4808-959b-c23d94cf0702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='form_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='form_submit']</value>
   </webElementProperties>
</WebElementEntity>
