<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PleaseConfirmPaymentType</description>
   <name>ConfirmPaymentType</name>
   <tag></tag>
   <elementGuidId>e4a0871e-4aac-4100-adfd-06e52c6bc77c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='paymentBind']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='paymentBind']</value>
   </webElementProperties>
</WebElementEntity>
