<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PolicyNo</name>
   <tag></tag>
   <elementGuidId>3dc93517-1e6e-4ac2-ab9e-bf716d6f888c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='quoteRecordsList']/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='quoteRecordsList']/tbody/tr[2]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
